env:
  browser: true
  commonjs: true
  es6: true
extends: 
  - 'eslint:recommended'
  - 'plugin:vue/recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  'vue/max-attributes-per-line': 3
  'vue/name-property-casing': 0
  'no-console': 'off'

